from __future__ import annotations

from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Mapping, Sequence

RARITY_ORDER = {"Mythic": 5, "Legendary": 4, "Rare": 3, "Uncommon": 2, "Common": 1}
RARITY_HTML_COLORS = {
    "Common": "#a0a0a0",
    "Uncommon": "#4caf50",
    "Rare": "#2196f3",
    "Legendary": "#ff9800",
    "Mythic": "#9c27b0",
}


def _fmt_age_ago(timestamp: int) -> str:
    age_seconds = int(datetime.now(timezone.utc).timestamp()) - int(timestamp)
    minutes, seconds = divmod(age_seconds, 60)
    hours, minutes = divmod(minutes, 60)
    days, hours = divmod(hours, 24)
    if days > 0:
        return f"{days}d {hours}h ago"
    if hours > 0:
        return f"{hours}h {minutes}m ago"
    if minutes > 0:
        return f"{minutes}m {seconds}s ago"
    return f"{seconds}s ago"


def generate_duck_dashboard_html(
    *,
    user_display_name: str,
    ducks: Sequence[Mapping[str, object]],
    output_path: Path,
) -> Path:
    normalized_ducks = [dict(duck) for duck in ducks]
    sorted_ducks = sorted(
        normalized_ducks,
        key=lambda d: RARITY_ORDER.get(str(d.get("rarity", "")), 0),
        reverse=True,
    )

    html = [
        "<html>",
        "<head>",
        f"<title>{escape(user_display_name)}'s Ducks</title>",
        "<style>",
        "body { font-family: Arial, sans-serif; background: #f0f8ff; margin: 0; padding: 20px; }",
        "h1 { text-align: center; color: #333; margin-bottom: 20px; }",
        ".controls { max-width: 1080px; margin: 0 auto 14px auto; display: flex; gap: 10px; flex-wrap: wrap; justify-content: center; }",
        ".controls input, .controls select { padding: 10px 12px; border-radius: 8px; border: 1px solid #c9d7e1; font-size: 14px; }",
        ".results-count { text-align: center; color: #4a5a66; margin-bottom: 16px; font-size: 14px; }",
        ".duck-grid { display: flex; flex-wrap: wrap; justify-content: center; gap: 20px; }",
        ".duck-card { background: white; border-radius: 12px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);",
        "             width: 220px; padding: 15px; text-align: center; transition: transform 0.2s; position: relative; cursor: pointer; }",
        ".duck-card:hover { transform: scale(1.05); }",
        ".duck-card img { border-radius: 8px; max-width: 100%; height: auto; margin-bottom: 10px; }",
        ".rarity { font-weight: bold; display: block; margin-top: 5px; }",
        ".stats { margin-top: 8px; font-size: 14px; color: #555; }",
        ".age { margin-top: 6px; font-size: 12px; color: #888; }",
        ".shiny { background: linear-gradient(135deg, #fffbe6, #ffffff); border: 3px solid gold;",
        "         box-shadow: 0 0 15px gold; animation: shine 1s infinite alternate; }",
        ".shiny::before { content: '✨ Shiny ✨'; position: absolute; top: -12px; right: -12px;",
        "                 background: gold; color: white; font-size: 12px; font-weight: bold;",
        "                 padding: 3px 6px; border-radius: 8px; box-shadow: 0 0 5px rgba(0,0,0,0.3); }",
        ".empty { text-align: center; color: #6b7d8a; margin-top: 30px; font-size: 16px; }",
        ".controls-note { text-align: center; color: #6b7d8a; margin-bottom: 22px; font-size: 13px; }",
        ".duck-modal { position: fixed; inset: 0; background: #0f1115; display: none; align-items: center;",
        "            justify-content: center; z-index: 9999; padding: 0; }",
        ".duck-modal.open { display: flex; }",
        ".duck-modal-card { position: relative; width: 100vw; height: 100vh; border-radius: 0; overflow: hidden; background: #0f1115; }",
        ".swipe-stage { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; padding: 12px; }",
        ".swipe-card { position: absolute; width: min(98vw, 640px); height: min(96vh, 1137px); aspect-ratio: 9 / 16;",
        "             border-radius: 18px; overflow: hidden; background: #111; box-shadow: 0 22px 50px rgba(0,0,0,0.45);",
        "             touch-action: none; }",
        ".swipe-card.next { transform: scale(0.96) translateY(8px); opacity: 0.78; }",
        ".swipe-card.front { z-index: 2; transition: transform 0.28s ease, opacity 0.28s ease; }",
        ".swipe-card.front.swipe-left { transform: translateX(-120%) rotate(-16deg); opacity: 0; }",
        ".swipe-card.front.swipe-right { transform: translateX(120%) rotate(16deg); opacity: 0; }",
        ".duck-modal-image-wrap { position: absolute; inset: 0; background: #111; }",
        ".duck-modal-image { width: 100%; height: 100%; object-fit: cover; display: block; }",
        ".duck-modal-overlay { position: absolute; inset: 0; background: linear-gradient(to top, rgba(0,0,0,0.76) 0%, rgba(0,0,0,0.4) 32%, rgba(0,0,0,0.12) 56%, rgba(0,0,0,0.05) 100%); }",
        ".duck-modal-body { position: absolute; left: 0; right: 0; bottom: 108px; padding: 18px 22px 0 22px; color: #fff; z-index: 2; }",
        ".duck-modal-title { margin: 0 0 6px 0; font-size: clamp(22px, 4vw, 34px); color: #fff; }",
        ".duck-modal-meta { margin: 0; color: #e8edf2; font-size: clamp(13px, 2.2vw, 17px); line-height: 1.45; }",
        ".swipe-badge { position: absolute; top: 14px; padding: 14px 22px; border: 5px solid; border-radius: 14px;",
        "              font-size: clamp(26px, 9vw, 56px); font-weight: 900; letter-spacing: 0.06em; opacity: 0;",
        "              text-transform: uppercase; line-height: 1.05; text-align: center;",
        "              transform: rotate(-14deg); z-index: 3; user-select: none; pointer-events: none;",
        "              text-shadow: 0 2px 0 rgba(0,0,0,0.25); box-shadow: 0 8px 24px rgba(0,0,0,0.35); }",
        ".swipe-badge .badge-sub { display: block; font-size: 0.42em; font-weight: 800; letter-spacing: 0.12em; margin-top: 6px; opacity: 0.95; }",
        ".swipe-badge.like { right: 10px; color: #1ED760; border-color: #1ED760; background: rgba(30,215,96,0.22); transform: rotate(14deg); }",
        ".swipe-badge.nope { left: 10px; color: #FF4454; border-color: #FF4454; background: rgba(255,68,84,0.22); }",
        ".duck-modal-actions { position: absolute; left: 0; right: 0; bottom: 24px; display: flex; gap: 16px; justify-content: center; z-index: 3; }",
        ".vote-btn { border: none; border-radius: 999px; width: 68px; height: 68px; font-size: 30px; cursor: pointer; transition: transform 0.12s ease; box-shadow: 0 8px 22px rgba(0,0,0,0.3); }",
        ".vote-btn:hover { transform: translateY(-1px); }",
        ".vote-nope { background: #ffe8ea; }",
        ".vote-like { background: #e8fff0; }",
        ".duck-modal-close { position: absolute; top: 10px; right: 10px; border: none; width: 34px; height: 34px;",
        "                 border-radius: 999px; background: rgba(0,0,0,0.56); color: #fff; font-size: 18px; cursor: pointer; z-index: 2; }",
        ".swipe-hint { position: absolute; left: 0; right: 0; bottom: 4px; text-align: center; color: rgba(255,255,255,0.8); font-size: 12px; z-index: 3; }",
        "@keyframes shine { from { box-shadow: 0 0 5px gold; } to { box-shadow: 0 0 20px gold; } }",
        "</style>",
        "</head>",
        "<body>",
        f"<h1>🦆 {escape(user_display_name)}'s Ducks</h1>",
    ]

    if not sorted_ducks:
        html.extend(
            [
                "<div class='controls'>",
                "<input type='search' placeholder='Search by duck name...' disabled>",
                "<select disabled><option>All rarities</option></select>",
                "<select disabled><option>Sort options</option></select>",
                "</div>",
                "<div class='controls-note'>Controls unlock once ducks are caught.</div>",
            ]
        )
        html.append("<p class='empty'>No ducks yet!</p>")
    else:
        html.extend(
            [
                "<div class='controls'>",
                "<input id='duck-search' type='search' placeholder='Search by duck name...'>",
                "<select id='rarity-filter'>",
                "<option value='all'>All rarities</option>",
                "<option value='Mythic'>Mythic</option>",
                "<option value='Legendary'>Legendary</option>",
                "<option value='Rare'>Rare</option>",
                "<option value='Uncommon'>Uncommon</option>",
                "<option value='Common'>Common</option>",
                "</select>",
                "<select id='shiny-filter'>",
                "<option value='all'>All ducks</option>",
                "<option value='shiny'>Shiny only</option>",
                "<option value='normal'>Non-shiny only</option>",
                "</select>",
                "<select id='sort-by'>",
                "<option value='rarity_desc'>Sort: Rarity (High to Low)</option>",
                "<option value='rarity_asc'>Sort: Rarity (Low to High)</option>",
                "<option value='name_asc'>Sort: Name (A-Z)</option>",
                "<option value='name_desc'>Sort: Name (Z-A)</option>",
                "<option value='newest'>Sort: Newest Caught</option>",
                "<option value='oldest'>Sort: Oldest Caught</option>",
                "<option value='attack_desc'>Sort: Attack (High to Low)</option>",
                "<option value='attack_asc'>Sort: Attack (Low to High)</option>",
                "<option value='defense_desc'>Sort: Defense (High to Low)</option>",
                "<option value='defense_asc'>Sort: Defense (Low to High)</option>",
                "<option value='speed_desc'>Sort: Speed (High to Low)</option>",
                "<option value='speed_asc'>Sort: Speed (Low to High)</option>",
                "</select>",
                "</div>",
                "<div class='results-count' id='results-count'></div>",
                "<div class='duck-grid' id='duck-grid'>",
            ]
        )

        for d in sorted_ducks:
            rarity = str(d.get("rarity", "Common"))
            rarity_color = RARITY_HTML_COLORS.get(rarity, "#000")
            timestamp = int(d.get("timestamp", 0))
            age_str = _fmt_age_ago(timestamp)
            is_shiny = bool(d.get("shiny", 0))
            card_class = "duck-card shiny" if is_shiny else "duck-card"
            name = str(d.get("name", "Unnamed Duck"))
            attack = int(d.get("attack", 0))
            defense = int(d.get("defense", 0))
            speed = int(d.get("speed", 0))
            total_power = attack + defense + speed
            url = str(d.get("url", ""))

            html.append(
                f"<div class='{card_class}' data-name='{escape(name.lower())}' "
                f"data-rarity='{escape(rarity)}' data-rarity-order='{RARITY_ORDER.get(rarity, 0)}' "
                f"data-timestamp='{timestamp}' data-shiny='{'1' if is_shiny else '0'}' "
                f"data-attack='{attack}' data-defense='{defense}' data-speed='{speed}' data-power='{total_power}'>"
                f"<img src='{escape(url)}' alt='{escape(name)}'>"
                f"<div><b>{escape(name)}</b></div>"
                f"<span class='rarity' style='color:{rarity_color};'>{escape(rarity)}</span>"
                f"<div class='stats'>⚔️ {attack} &nbsp; 🛡️ {defense} &nbsp; 💨 {speed}</div>"
                f"<div class='age'>Caught {escape(age_str)}</div>"
                f"</div>"
            )

        html.extend(
            [
                "</div>",
                "<div class='duck-modal' id='duck-modal'>",
                "<div class='duck-modal-card' id='duck-modal-card'>",
                "<div class='swipe-stage'>",
                "<div class='swipe-card next' id='swipe-next'>",
                "<div class='duck-modal-image-wrap'>",
                "<img class='duck-modal-image' id='duck-modal-image-next' alt='Next duck photo'>",
                "<div class='duck-modal-overlay'></div>",
                "</div>",
                "</div>",
                "<div class='swipe-card front' id='swipe-front'>",
                "<div class='duck-modal-image-wrap'>",
                "<button class='duck-modal-close' id='duck-modal-close' type='button' aria-label='Close viewer'>✕</button>",
                "<img class='duck-modal-image' id='duck-modal-image' alt='Duck photo'>",
                "<div class='duck-modal-overlay'></div>",
                "<div class='swipe-badge nope' id='badge-nope'>NAH<span class='badge-sub'>wrong pond 💀</span></div>",
                "<div class='swipe-badge like' id='badge-like'>YAS<span class='badge-sub'>duck of my dreams 🦆</span></div>",
                "</div>",
                "<div class='duck-modal-body'>",
                "<h2 class='duck-modal-title' id='duck-modal-title'></h2>",
                "<p class='duck-modal-meta' id='duck-modal-meta'></p>",
                "</div>",
                "<div class='duck-modal-actions'>",
                "<button class='vote-btn vote-nope' id='vote-nope' type='button' title='Dislike and next'>🤮</button>",
                "<button class='vote-btn vote-like' id='vote-like' type='button' title='Like and next'>❤️</button>",
                "</div>",
                "<div class='swipe-hint'>Swipe left/right (or drag) to browse</div>",
                "</div>",
                "</div>",
                "</div>",
                "<script>",
                "const searchInput = document.getElementById('duck-search');",
                "const rarityFilter = document.getElementById('rarity-filter');",
                "const shinyFilter = document.getElementById('shiny-filter');",
                "const sortBy = document.getElementById('sort-by');",
                "const resultsCount = document.getElementById('results-count');",
                "const grid = document.getElementById('duck-grid');",
                "const cards = Array.from(grid.querySelectorAll('.duck-card'));",
                "const modal = document.getElementById('duck-modal');",
                "const modalCard = document.getElementById('duck-modal-card');",
                "const swipeFront = document.getElementById('swipe-front');",
                "const swipeNext = document.getElementById('swipe-next');",
                "const modalImg = document.getElementById('duck-modal-image');",
                "const modalImgNext = document.getElementById('duck-modal-image-next');",
                "const badgeNope = document.getElementById('badge-nope');",
                "const badgeLike = document.getElementById('badge-like');",
                "const modalTitle = document.getElementById('duck-modal-title');",
                "const modalMeta = document.getElementById('duck-modal-meta');",
                "const modalClose = document.getElementById('duck-modal-close');",
                "const voteNope = document.getElementById('vote-nope');",
                "const voteLike = document.getElementById('vote-like');",
                "let visibleCards = [];",
                "let activeIndex = 0;",
                "let swipeStartX = null;",
                "let isAnimating = false;",
                "let pointerStartX = 0;",
                "let pointerStartY = 0;",
                "let currentDx = 0;",
                "let currentDy = 0;",
                "let isPointerDown = false;",
                "",
                "function applyControls() {",
                "  const query = searchInput.value.trim().toLowerCase();",
                "  const selectedRarity = rarityFilter.value;",
                "  const selectedShiny = shinyFilter.value;",
                "  const sortValue = sortBy.value;",
                "",
                "  const visible = cards.filter((card) => {",
                "    const name = card.dataset.name || '';",
                "    const rarity = card.dataset.rarity || '';",
                "    const shiny = card.dataset.shiny || '0';",
                "    const matchesSearch = !query || name.includes(query);",
                "    const matchesRarity = selectedRarity === 'all' || rarity === selectedRarity;",
                "    const matchesShiny = selectedShiny === 'all' || (selectedShiny === 'shiny' ? shiny === '1' : shiny === '0');",
                "    const visibleNow = matchesSearch && matchesRarity && matchesShiny;",
                "    card.style.display = visibleNow ? '' : 'none';",
                "    return visibleNow;",
                "  });",
                "",
                "  visible.sort((a, b) => {",
                "    const rarityA = Number(a.dataset.rarityOrder || '0');",
                "    const rarityB = Number(b.dataset.rarityOrder || '0');",
                "    const nameA = a.dataset.name || '';",
                "    const nameB = b.dataset.name || '';",
                "    const tsA = Number(a.dataset.timestamp || '0');",
                "    const tsB = Number(b.dataset.timestamp || '0');",
                "    const attackA = Number(a.dataset.attack || '0');",
                "    const attackB = Number(b.dataset.attack || '0');",
                "    const defenseA = Number(a.dataset.defense || '0');",
                "    const defenseB = Number(b.dataset.defense || '0');",
                "    const speedA = Number(a.dataset.speed || '0');",
                "    const speedB = Number(b.dataset.speed || '0');",
                "",
                "    if (sortValue === 'rarity_asc') return rarityA - rarityB;",
                "    if (sortValue === 'name_asc') return nameA.localeCompare(nameB);",
                "    if (sortValue === 'name_desc') return nameB.localeCompare(nameA);",
                "    if (sortValue === 'newest') return tsB - tsA;",
                "    if (sortValue === 'oldest') return tsA - tsB;",
                "    if (sortValue === 'attack_desc') return attackB - attackA;",
                "    if (sortValue === 'attack_asc') return attackA - attackB;",
                "    if (sortValue === 'defense_desc') return defenseB - defenseA;",
                "    if (sortValue === 'defense_asc') return defenseA - defenseB;",
                "    if (sortValue === 'speed_desc') return speedB - speedA;",
                "    if (sortValue === 'speed_asc') return speedA - speedB;",
                "    return rarityB - rarityA;",
                "  });",
                "",
                "  visible.forEach((card) => grid.appendChild(card));",
                "  resultsCount.textContent = `Showing ${visible.length} of ${cards.length} ducks`;",
                "  visibleCards = visible;",
                "}",
                "",
                "function cardDetails(card) {",
                "  const name = card.dataset.name || '';",
                "  const rarity = card.dataset.rarity || 'Unknown';",
                "  const attack = card.dataset.attack || '0';",
                "  const defense = card.dataset.defense || '0';",
                "  const speed = card.dataset.speed || '0';",
                "  const img = card.querySelector('img');",
                "  const age = card.querySelector('.age')?.textContent || '';",
                "  return {",
                "    displayName: card.querySelector('b')?.textContent || name,",
                "    rarity, attack, defense, speed, age,",
                "    image: img ? img.getAttribute('src') || '' : ''",
                "  };",
                "}",
                "",
                "function renderModal(index) {",
                "  if (!visibleCards.length) return;",
                "  activeIndex = (index + visibleCards.length) % visibleCards.length;",
                "  const detail = cardDetails(visibleCards[activeIndex]);",
                "  modalImg.src = detail.image;",
                "  modalImg.alt = detail.displayName;",
                "  modalTitle.textContent = detail.displayName;",
                "  modalMeta.textContent = `${detail.rarity} | ⚔️ ${detail.attack}  🛡️ ${detail.defense}  💨 ${detail.speed} | ${detail.age}`;",
                "  const nextDetail = cardDetails(visibleCards[(activeIndex + 1) % visibleCards.length]);",
                "  modalImgNext.src = nextDetail.image;",
                "  modalImgNext.alt = nextDetail.displayName;",
                "  resetFrontCardTransform();",
                "}",
                "",
                "function openModalForCard(card) {",
                "  if (!visibleCards.length) return;",
                "  const idx = visibleCards.indexOf(card);",
                "  renderModal(idx >= 0 ? idx : 0);",
                "  modal.classList.add('open');",
                "}",
                "",
                "function closeModal() {",
                "  modal.classList.remove('open');",
                "  resetFrontCardTransform();",
                "}",
                "",
                "function clamp(v, min, max) { return Math.max(min, Math.min(max, v)); }",
                "",
                "function resetFrontCardTransform() {",
                "  swipeFront.style.transform = '';",
                "  badgeLike.style.opacity = '0';",
                "  badgeNope.style.opacity = '0';",
                "}",
                "",
                "function updateDragVisual(dx, dy) {",
                "  currentDx = dx;",
                "  currentDy = dy;",
                "  const rotate = clamp(dx / 16, -18, 18);",
                "  const scale = 0.99 + Math.min(Math.abs(dx) / 1200, 0.01);",
                "  swipeFront.style.transform = `translate(${dx}px, ${dy}px) rotate(${rotate}deg) scale(${scale})`;",
                "  badgeLike.style.opacity = String(clamp(dx / 120, 0, 1));",
                "  badgeNope.style.opacity = String(clamp(-dx / 120, 0, 1));",
                "}",
                "",
                "function swipeToNext(direction) {",
                "  if (isAnimating || !visibleCards.length) return;",
                "  isAnimating = true;",
                "  isPointerDown = false;",
                "  swipeFront.classList.remove('swipe-left', 'swipe-right');",
                "  swipeFront.style.transform = '';",
                "  swipeFront.classList.add(direction === 'left' ? 'swipe-left' : 'swipe-right');",
                "  badgeLike.style.opacity = direction === 'right' ? '1' : '0';",
                "  badgeNope.style.opacity = direction === 'left' ? '1' : '0';",
                "  setTimeout(() => {",
                "    swipeFront.classList.remove('swipe-left', 'swipe-right');",
                "    renderModal(activeIndex + 1);",
                "    isAnimating = false;",
                "  }, 280);",
                "}",
                "",
                "function onPointerDown(clientX, clientY) {",
                "  if (isAnimating || !modal.classList.contains('open')) return;",
                "  isPointerDown = true;",
                "  pointerStartX = clientX;",
                "  pointerStartY = clientY;",
                "  currentDx = 0;",
                "  currentDy = 0;",
                "  swipeFront.style.transition = 'none';",
                "}",
                "",
                "function onPointerMove(clientX, clientY) {",
                "  if (!isPointerDown || isAnimating) return;",
                "  const dx = clientX - pointerStartX;",
                "  const dy = (clientY - pointerStartY) * 0.22;",
                "  updateDragVisual(dx, dy);",
                "}",
                "",
                "function onPointerUp() {",
                "  if (!isPointerDown || isAnimating) return;",
                "  isPointerDown = false;",
                "  swipeFront.style.transition = 'transform 0.22s ease, opacity 0.22s ease';",
                "  if (Math.abs(currentDx) > 95) {",
                "    swipeToNext(currentDx > 0 ? 'right' : 'left');",
                "    return;",
                "  }",
                "  resetFrontCardTransform();",
                "}",
                "",
                "cards.forEach((card) => {",
                "  card.addEventListener('click', () => openModalForCard(card));",
                "});",
                "voteLike.addEventListener('click', () => swipeToNext('right'));",
                "voteNope.addEventListener('click', () => swipeToNext('left'));",
                "modalClose.addEventListener('click', closeModal);",
                "modal.addEventListener('click', (e) => { if (e.target === modal) closeModal(); });",
                "document.addEventListener('keydown', (e) => {",
                "  if (!modal.classList.contains('open')) return;",
                "  if (e.key === 'Escape') closeModal();",
                "  else if (e.key === 'ArrowRight') swipeToNext('right');",
                "  else if (e.key === 'ArrowLeft') swipeToNext('left');",
                "});",
                "",
                "function onSwipeStart(clientX) { swipeStartX = clientX; }",
                "function onSwipeEnd(clientX) {",
                "  if (swipeStartX === null) return;",
                "  const delta = clientX - swipeStartX;",
                "  swipeStartX = null;",
                "  if (Math.abs(delta) < 40) return;",
                "  if (delta < 0) swipeToNext('left'); else swipeToNext('right');",
                "}",
                "swipeFront.addEventListener('touchstart', (e) => {",
                "  const t = e.touches[0];",
                "  onSwipeStart(t.clientX);",
                "  onPointerDown(t.clientX, t.clientY);",
                "}, { passive: true });",
                "swipeFront.addEventListener('touchmove', (e) => {",
                "  const t = e.touches[0];",
                "  onPointerMove(t.clientX, t.clientY);",
                "}, { passive: true });",
                "swipeFront.addEventListener('touchend', (e) => {",
                "  const t = e.changedTouches[0];",
                "  onSwipeEnd(t.clientX);",
                "  onPointerUp();",
                "});",
                "swipeFront.addEventListener('mousedown', (e) => {",
                "  onSwipeStart(e.clientX);",
                "  onPointerDown(e.clientX, e.clientY);",
                "});",
                "window.addEventListener('mousemove', (e) => onPointerMove(e.clientX, e.clientY));",
                "window.addEventListener('mouseup', (e) => {",
                "  if (!isPointerDown) return;",
                "  onSwipeEnd(e.clientX);",
                "  onPointerUp();",
                "});",
                "",
                "searchInput.addEventListener('input', applyControls);",
                "rarityFilter.addEventListener('change', applyControls);",
                "shinyFilter.addEventListener('change', applyControls);",
                "sortBy.addEventListener('change', applyControls);",
                "applyControls();",
                "</script>",
            ]
        )

    html.append("</body></html>")
    output_path.write_text("\n".join(html), encoding="utf-8")
    return output_path
